オブジェクト指向の活用

【問題1】これまで利用してきたクラスの列挙

・Pandas ・・・ DataFrame

・matplotlib　・・・　pyplot

・scikit-learn　・・・　LogisticRegression

【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。
（５つ以上）

１　numpyのarrayメソッド

２　pyplotのplotメソッド

３　DataFrameの.locアトリビュート

４　DataFrameの.Tアトリビュート

５　pyplotのscatterメソッド

【問題3】標準化クラスをスクラッチで作成

In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_=np.mean(X,axis=0)
        self.var_=np.var(X,axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled=(X-self.mean_)/np.sqrt(self.var_)

        return X_scaled

In [2]:
#　サンプルコードを行ってみる

import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


【問題4】 四則演算を行うクラスの作成

In [11]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        if type(value)==int or type(value)==float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print("エラー")
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def hiku(self, value2):
        """
        受け取った引数をself.valueから引き算をする
        """
        self.value -= value2
    def kakeru(self, value2):
        """
        受け取った引数をself.valueで掛け算をする
        """
        self.value *= value2
    def waru(self, value2):
        """
        受け取った引数をself.valueで割り算をする
        """
        self.value /= value2

In [12]:
#　出力例１
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


In [13]:
#　出力例２　配列を入れてエラーを出す
example = ExampleClass([2,3])

エラー
