【問題1】行列積を手計算する

AB11を行列Aと行列Bの積の1行1列の成分とする

AB11=0+0+6=6
AB12=-2+4+27=29
AB13=-1-16-3=-20

AB21=0+0+12=12
AB22=8-10+54=52
AB23=4+40-6=38

AB31=0+0-18=-18
AB32=14+16-81=-51
AB33=7-64+9=-48

よってABは
[6,29,-20]
[12,52,38]
[-18,-51,-48]
となる

【問題2】NumPyの関数による計算

In [5]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# np.matmul()で計算
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# np.dot()で計算
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# @で計算
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題3】ある要素の計算を実装

In [19]:
# AB11の計算式のプログラミング

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

sigma00=a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
print(sigma00)

6


【問題4】行列積を行う関数の作成

In [20]:
# 3×3の行列の積を出力

def chida(a,b):
    import numpy as np
    a_ndarray = np.array(a)
    b_ndarray = np.array(b)
    sigma00=a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
    sigma01=a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
    sigma02=a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]
    sigma10=a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
    sigma11=a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
    sigma12=a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]
    sigma20=a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
    sigma21=a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
    sigma22=a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
    
    matrix=np.array([[sigma00,sigma01,sigma02], [sigma10,sigma11,sigma12], [sigma20,sigma21,sigma22]])
    return matrix

a = ([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = ([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

chida(a,b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題5】計算が定義されない入力を判定する

In [40]:
# 行列が3×3じゃない場合計は「計算ができません」と表示させる
# 例として計算ができる場合とできない場合を表示

def chida(a,b):
    import numpy as np
    a_ndarray = np.array(a)
    b_ndarray = np.array(b)
    if a_ndarray.shape==b_ndarray.shape:
        sigma00=a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
        sigma01=a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
        sigma02=a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]
        sigma10=a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
        sigma11=a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
        sigma12=a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]
        sigma20=a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
        sigma21=a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
        sigma22=a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
    
        matrix=np.array([[sigma00,sigma01,sigma02], [sigma10,sigma11,sigma12], [sigma20,sigma21,sigma22]])
        return matrix
    else:
        print("計算ができません")

a = ([[-1, 2, 3], [4, -5, 6],[7, 8, -9]])
b = ([[0, 2, 1], [0, 2, -8],[2, 9, -1]])

print(chida(a,b))

a = ([[-1, 2, 3], [4, -5, 6],[7, 8, -9]])
b = ([[0, 2, 1], [0, 2, -8]])

chida(a,b)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
計算ができません


【問題6】転置

In [44]:

import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# d_ndarrayを転置し、３×２と２×３の行列として計算

d_ndarray2=d_ndarray.T

d_ndarray.T @ e_ndarray

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])