【問題1】SimpleRNNのフォワードプロパゲーション実装  
クラスを制作した

In [67]:
class RNN_sample():
  
  def RNN_forward_calculate(self,x,w_x,w_h): 
    batch_size = x.shape[0] # 1
    n_sequences = x.shape[1] # 3
    n_features = x.shape[2] # 2
    n_nodes = w_x.shape[1] # 4
    self.h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
    b = np.ones(n_nodes) 

    for i in range(n_sequences):
      a=x[0,i]@w_x+self.h@w_h+b
      self.h=np.tanh(a)
    h=self.h
    return h

【問題2】小さな配列でのフォワードプロパゲーションの実験

In [77]:
# テキストの例の読み込みを行う

import numpy as np
x = np.array([[[1, 2], [2, 3], [3, 4]]])/100 # (batch_size, n_sequences, n_features)
w_x = np.array([[1, 3, 5, 7], [3, 5, 7, 8]])/100 # (n_features, n_nodes)
w_h = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 5, 7, 8], [4, 6, 8, 10]])/100 # (n_nodes, n_nodes)
batch_size = x.shape[0] # 1
n_sequences = x.shape[1] # 3
n_features = x.shape[2] # 2
n_nodes = w_x.shape[1] # 4
h = np.zeros((batch_size, n_nodes)) # (batch_size, n_nodes)
b = np.array([1, 1, 1, 1]) # (n_nodes,)

In [69]:
# 問題１で作ったクラスを実行してみる

RNN1=RNN_sample()
RNN1.RNN_forward_calculate(x,w_x,w_h)

array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])

In [71]:
# こちらが期待される出力、一致していることがわかった

h = np.array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]]) 
h

array([[0.79494228, 0.81839002, 0.83939649, 0.85584174]])

ここから下は、自分の復習のためのフォワードプロバゲーションを１つずつ実行したものである

In [78]:
x

array([[[0.01, 0.02],
        [0.02, 0.03],
        [0.03, 0.04]]])

In [79]:
w_x

array([[0.01, 0.03, 0.05, 0.07],
       [0.03, 0.05, 0.07, 0.08]])

In [80]:
w_h

array([[0.01, 0.03, 0.05, 0.07],
       [0.02, 0.04, 0.06, 0.08],
       [0.03, 0.05, 0.07, 0.08],
       [0.04, 0.06, 0.08, 0.1 ]])

In [81]:
h

array([[0., 0., 0., 0.]])

In [82]:
a1=x[0,0]@w_x+h@w_h+b
print(a1)
h1=np.tanh(a1)
print(h1)
a2=x[0,1]@w_x+h1@w_h+b
print(a2)
h2=np.tanh(a2)
print(h2)
a3=x[0,2]@w_x+h2@w_h+b
print(a3)
h3=np.tanh(a3)
print(h3)

[[1.0007 1.0013 1.0019 1.0023]]
[[0.76188798 0.76213958 0.76239095 0.76255841]]
[[1.07733574 1.13931527 1.20129481 1.25535044]]
[[0.792209   0.8141834  0.83404912 0.84977719]]
[[1.08471832 1.15192269 1.21912707 1.27759095]]
[[0.79494228 0.81839002 0.83939649 0.85584174]]
